apiVersion: v1
kind: Secret
metadata:
  name: airflow-metadata-connection
type: Opaque
stringData:
  # Airflow chart expects key 'connection'
  # Example: postgresql+psycopg2://user:pass@host:5432/airflow
  connection: postgresql+psycopg2://airflow:airflow@postgres.example.local:5432/airflow
