apiVersion: v1
kind: Secret
metadata:
  name: airflow-metadata-connection
type: Opaque
stringData:
  # Airflow chart expects key 'connection'
  # External metadata DB for Airflow.
  connection: postgresql+psycopg2://postgres:postgres@host.docker.internal:5432/airflow_db
