apiVersion: v1
kind: Secret
metadata:
  name: airflow-connections
type: Opaque
stringData:
  AIRFLOW_CONN_DWH_EGISZ_PG: "postgres://egisz:egisz@host.docker.internal:5432/dwh_egisz?sslmode=disable"
  AIRFLOW_CONN_PROXY_EGISZ_FB: "firebird://SYSDBA:masterkey@host.docker.internal:3050/proxy_egisz?charset=WIN1251"
