apiVersion: v1
kind: Service
metadata:
  name: metabase
  labels:
    app.kubernetes.io/name: metabase
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: metabase
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
  labels:
    app.kubernetes.io/name: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: metabase
  template:
    metadata:
      labels:
        app.kubernetes.io/name: metabase
    spec:
      containers:
        - name: metabase
          image: metabase/metabase:v0.49.14
          ports:
            - containerPort: 3000
              name: http
          env:
            # Metabase application DB (external Postgres)
            - name: MB_DB_TYPE
              value: postgres
            - name: MB_DB_HOST
              value: host.docker.internal
            - name: MB_DB_PORT
              value: "5432"
            - name: MB_DB_DBNAME
              value: dwh_egisz
            - name: MB_DB_USER
              value: egisz
            - name: MB_DB_PASS
              value: egisz
